#!/usr/bin/env python3
"""
根据chinese_calendar库生成Go语言的节假日数据表
"""
import datetime
import chinese_calendar

def get_compensation_pairs(year):
    mapping = {}
    detail_to_workdays = {}
    for d, detail in chinese_calendar.workdays.items():
        if d.year == year:
            if detail not in detail_to_workdays:
                detail_to_workdays[detail] = []
            detail_to_workdays[detail].append(d)
    
    detail_to_holidays = {}
    for d, detail in chinese_calendar.holidays.items():
        if d.year == year and chinese_calendar.is_in_lieu(d):
            if detail not in detail_to_holidays:
                detail_to_holidays[detail] = []
            detail_to_holidays[detail].append(d)
    
    for detail, holidays in detail_to_holidays.items():
        workdays = detail_to_workdays.get(detail, [])
        if workdays:
            for h, w in zip(sorted(holidays), sorted(workdays)):
                mapping[h] = w
    return mapping

def generate_go_code():
    lines = []
    lines.append("// Code generated by gen_table.py. DO NOT EDIT.")
    lines.append("")
    lines.append("package valence")
    lines.append("")
    
    # 节假日数据表
    lines.append("// 节假日数据表")
    lines.append("var holidayTable = map[string]bool{")
    for year in range(2004, datetime.datetime.now().year):
        start_date = datetime.date(year, 1, 1)
        end_date = datetime.date(year, 12, 31)
        current_date = start_date
        while current_date <= end_date:
            is_holiday = chinese_calendar.is_holiday(current_date)
            if is_holiday:
                date_str = current_date.strftime("%Y-%m-%d")
                lines.append(f'    "{date_str}": true,')
            current_date += datetime.timedelta(days=1)
    lines.append("}")
    lines.append("")
    
    # 调休标记表
    lines.append("// 调休标记表")
    lines.append("var inLieuTable = map[string]bool{")
    for year in range(2004, datetime.datetime.now().year):
        start_date = datetime.date(year, 1, 1)
        end_date = datetime.date(year, 12, 31)
        current_date = start_date
        while current_date <= end_date:
            if current_date in chinese_calendar.in_lieu_days:
                date_str = current_date.strftime("%Y-%m-%d")
                lines.append(f'    "{date_str}": true,')
            current_date += datetime.timedelta(days=1)
    lines.append("}")
    lines.append("")
    
    # 调休配对表
    lines.append("// 调休配对表")
    lines.append("var compensationTable = map[string]string{")
    for year in range(2004, datetime.datetime.now().year):
        pairs = get_compensation_pairs(year)
        for holiday_date, workday_date in pairs.items():
            holiday_str = holiday_date.strftime("%Y-%m-%d")
            workday_str = workday_date.strftime("%Y-%m-%d")
            lines.append(f'    "{holiday_str}": "{workday_str}",')
    lines.append("}")
    lines.append("")
    
    return "\n".join(lines)

if __name__ == "__main__":
    print("正在生成Go节假日数据表...")
    go_code = generate_go_code()
    with open("model.go", "w", encoding="utf-8") as f:
        f.write(go_code)
    print("完成! 生成的 model.go 文件包含节假日数据表。")