#!/usr/bin/env python3
"""
根据 chinese_calendar 库生成 Go 语言的节假日数据表
参考 FastClassSchedule/utils/calc.py 中的逻辑
"""
import datetime
import chinese_calendar


def _holiday_to_workday_map(year):
    """
    构建指定年份的映射：调休休息日(holiday 且 in_lieu) -> 对应补班日(workday)。
    规则：按 detail 归组；组内分别对"调休休息日"和"补班日"排序后按序配对；zip 最短长度保证稳健。
    """
    # detail -> list[workday]
    detail_to_workdays = {}
    for d, detail in chinese_calendar.workdays.items():
        if d.year == year:
            detail_to_workdays.setdefault(detail, []).append(d)

    # detail -> list[in-lieu holiday]
    detail_to_holidays = {}
    for d, detail in chinese_calendar.holidays.items():
        if d.year == year and chinese_calendar.is_in_lieu(d):
            detail_to_holidays.setdefault(detail, []).append(d)

    mapping = {}
    for detail, holidays in detail_to_holidays.items():
        workdays = detail_to_workdays.get(detail, [])
        if not workdays:
            continue
        for h, w in zip(sorted(holidays), sorted(workdays)):
            mapping[h] = w
    return mapping


def generate_go_code():
    lines = []
    lines.append("// Code generated by gen_table.py. DO NOT EDIT.")
    lines.append("")
    lines.append("package valence")
    lines.append("")
    
    # 节假日数据表
    lines.append("// 节假日数据表")
    lines.append("var holidayTable = map[string]bool{")
    for year in range(2004, datetime.datetime.now().year + 1):
        start_date = datetime.date(year, 1, 1)
        end_date = datetime.date(year, 12, 31)
        current_date = start_date
        while current_date <= end_date:
            if chinese_calendar.is_holiday(current_date):
                date_str = current_date.strftime("%Y-%m-%d")
                lines.append(f'    "{date_str}": true,')
            current_date += datetime.timedelta(days=1)
    lines.append("}")
    lines.append("")
    
    # 调休休息日标记表
    lines.append("// 调休休息日标记表 (调休产生的休息日、处于调休链条中的日期)")
    lines.append("var inLieuTable = map[string]bool{")
    for year in range(2004, datetime.datetime.now().year + 1):
        start_date = datetime.date(year, 1, 1)
        end_date = datetime.date(year, 12, 31)
        current_date = start_date
        while current_date <= end_date:
            if chinese_calendar.is_in_lieu(current_date):
                date_str = current_date.strftime("%Y-%m-%d")
                lines.append(f'    "{date_str}": true,')
            current_date += datetime.timedelta(days=1)
    lines.append("}")
    lines.append("")
    
    # 调休配对表：调休休息日 -> 对应的补班日
    lines.append("// 调休配对表：调休休息日 -> 补班日")
    lines.append("var compensationTable = map[string]string{")
    for year in range(2004, datetime.datetime.now().year + 1):
        pairs = _holiday_to_workday_map(year)
        for holiday_date, workday_date in sorted(pairs.items()):
            holiday_str = holiday_date.strftime("%Y-%m-%d")
            workday_str = workday_date.strftime("%Y-%m-%d")
            lines.append(f'    "{holiday_str}": "{workday_str}",')
    lines.append("}")
    lines.append("")
    
    return "\n".join(lines)


if __name__ == "__main__":
    print("正在生成 Go 节假日数据表...")
    go_code = generate_go_code()
    with open("model.go", "w", encoding="utf-8") as f:
        f.write(go_code)
    print("完成! 生成的 model.go 文件包含节假日数据表。")